### ISSUE TITLE
Names for devices are all the same on iOS 16

### ISSUE THREAD

**Issue by xorguy** [grzegorz914/homebridge-enphase-envoy#58] opened 2022-10-11 07:37 UTC
After updating to iOS 16, even latest 16.0.3, with Eve app all devices exposed at HomeKit have the same name "Envoy-S Cxxx". With iOS 15 there was Power consumption, Power production, etc...

Now it is very difficult to know for sure which device is the one you want to check.

Is there any way to have the names as before with iOS 16?

Thanks.

**Comment by grzegorz914** [comment] 2022-12-10 17:17
This is know issue with iOS 16.x, no solution yet.

**Comment by grzegorz914** [comment] 2023-01-09 16:01
I close this because not a bug from plugin.

**Closed by grzegorz914** 2023-01-09 16:01 UTC
